name: Deploy Site on fschatbot.github.io

on:
  push:
    branch: [master]

jobs:
  FULL_DEPLOY:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - env:
          AUTH_TOKEN_FOR_DEPLOYMENT: ${{ secrets.AUTH_TOKEN_FOR_DEPLOYMENT }}
          FOLDER_NAME: Home-Page
        run: |
          npm ci --no-audit --silent
          npm run build

          rm -rf .git
          mv build $FOLDER_NAME
          git init --quiet
          git config user.name "fschatbot"
          git config user.email "s.himanshu.sultania@fountainheadschools.org"

          git add $FOLDER_NAME
          git commit -m "Deploy to GitHub Pages"
          git remote add origin "https://$AUTH_TOKEN_FOR_DEPLOYMENT@github.com/fschatbot/fschatbot.github.io.git"
          git checkout --quiet -b Server-Mode
          git push --force --quiet -u origin Server-Mode
