name: Deploy Site on fschatbot.github.io

on:
  push:
    branch: [master]

jobs:
  FULL_DEPLOY:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - env:
          AUTH_TOKEN_FOR_DEPLOYMENT: ${{ secrets.AUTH_TOKEN_FOR_DEPLOYMENT }}
          COMMIT_MESSAGE: ${{ github.event.commits[0].message }}
        name: Deploy Site
        run: |
          echo "Create The Build"
          rm -rf .git
          npm ci --no-audit
          npm run build
          mkdir repo
          cd repo

          echo "Setup Git"
          git init
          git config --local user.name "fschatbot"
          git config --local user.email "s.himanshu.sultania@fountainheadschools.org"

          echo "Make the Repo Authentic with changes"
          git remote add origin "https://$AUTH_TOKEN_FOR_DEPLOYMENT@github.com/fschatbot/fschatbot.github.io.git"
          git pull origin Github-Page
          cp ../build/* . -r

          ls -R -I node_modules

          echo "Deploy"
          git add .
          git commit -m "$COMMIT_MESSAGE"
          git push -u origin master:Github-Page
