name: Deploy Site on fschatbot.github.io

on:
  push:
    branch: [master]

jobs:
  FULL_DEPLOY:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - env:
          GITHUB_AUTH_TOKEN_FOR_DEPLOYMENT: ${{ secrets.GITHUB_AUTH_TOKEN_FOR_DEPLOYMENT }}
        run: |
          npm ci
          npm run build

          rm -rf .git
          cd build
          git init
          git config user.name "fschatbot"
          git config user.email "s.himanshu.sultania@fountainheadschools.org"

          git add .
          git commit -m "Deploy to GitHub Pages"
          git push --force --quiet "https://$GITHUB_AUTH_TOKEN_FOR_DEPLOYMENT@github.com/fschatbot/fschatbot.github.io.git" Server-Mode:gh-pages
