name: Deploy Site on fschatbot.github.io

on:
  push:
    branch: [master]

jobs:
  cancel-previous-runs:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ secrets.AUTH_TOKEN_FOR_DEPLOYMENT }}
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Create the build
        run: |
          rm -rf .git
          npm ci --no-audit --no-fund
          curl https://programming-quotes-api.herokuapp.com/quotes -o src/components/Quotes.json
          CI='' npm run build
          mkdir repo
      - name: Setup Git
        run: |
          cd repo
          git init
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Make the Repo Authentic with changes
        run: |
          cd repo
          git remote add origin "https://${{ secrets.AUTH_TOKEN_FOR_DEPLOYMENT }}@github.com/fschatbot/fschatbot.github.io.git"
          git pull origin Github-Page
          cp ../build/* . -r
      - name: Deploy Site
        run: |
          cd repo
          git add .
          git commit -m "${{ github.event.head_commit.message }} (${{ github.event.head_commit.id }}) [ci skip]"
          git push -u origin master:Github-Page
