name: Deploy Site on fschatbot.github.io

on:
  push:
    branch: [master]

jobs:
  FULL_DEPLOY:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Create The Build
        run: |
          rm -rf .git
          npm ci --no-audit
          npm run build
          cd build
      - name: Setup git
        run: |
          git init
          git config --local user.name "fschatbot"
          git config --local user.email "s.himanshu.sultania@fountainheadschools.org"

          git remote add origin "https://${{ secrets.AUTH_TOKEN_FOR_DEPLOYMENT }}@github.com/fschatbot/fschatbot.github.io.git"
          git pull origin Github-Page
      - name: Deploy
        run: |
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push -u origin master:Github-Page
