name: Deploy Site on fschatbot.github.io

on:
  push:
    branch: [master]

jobs:
  FULL_DEPLOY:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - env:
          AUTH_TOKEN_FOR_DEPLOYMENT: ${{ secrets.AUTH_TOKEN_FOR_DEPLOYMENT }}
          FOLDER_NAME: Home-Page
        run: |
          npm ci --no-audit
          npm run build

          rm -rf .git
          mkdir repo
          cd repo
          git init
          git config user.name "fschatbot"
          git config user.email "s.himanshu.sultania@fountainheadschools.org"

          git remote add origin "https://$AUTH_TOKEN_FOR_DEPLOYMENT@github.com/fschatbot/fschatbot.github.io.git"
          git fetch origin Server-Mode
          rm -rf $FOLDER_NAME

          cd ..
          mv build repo/$FOLDER_NAME
          cd repo

          git add $FOLDER_NAME
          git commit -m "Deploy to GitHub Pages"

          git push -u origin master:Server-Mode
