# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: rm -rf .git
      # re-initialise git
    - run: git init
    - run: git config user.name "fschatbot"
    - run: git config user.email "s.himanshu.sultania@fountainheadschools.org"
    - run: git remote set-url origin https://fschatbot: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@github.com/fschatbot/fschatbot.github.io.git
      # add and commit /docs/ folder
    - run: git add home
    - run: git commit -m "deploy the bundle"
      # push the commit to the public repository
    - run: git push origin HEAD:Server-Mode --force
